import GameCard from "@/components/GameCard";
import AccuracyPanel from "@/components/AccuracyPanel";
import { getAccuracyStats, getRecentForm } from "@/lib/store";
import { getGamesData } from "@/lib/games";

export default async function Home() {
  const [{ games, source, error }, accuracy, recentForm] = await Promise.all([
    getGamesData(),
    getAccuracyStats().catch(() => ({ gamesEvaluated: 0, winnerAccuracy: 0, avgTotalError: 0, avgMarginError: 0 })),
    getRecentForm(10).catch(() => [] as boolean[]),
  ]);

  return (
    <main className="min-h-screen max-w-3xl mx-auto px-4 py-10">
      <header className="mb-8">
        <p className="font-display text-amber text-sm tracking-[0.3em] uppercase mb-2">
          Court Line
        </p>
        <h1 className="font-display text-4xl md:text-5xl leading-tight">
          NBA Score Predictor
        </h1>
        <p className="text-chalk/60 mt-3 max-w-xl">
          Statistical picks for the three core bet types — Winner,
          Total Points (O/U), and Handicap — generated from our own
          team-stats model, blended with Elo ratings that update after
          every finished game.
        </p>
        {source === "mock" && (
          <p className="text-xs text-buzzer mt-4 border border-buzzer/40 inline-block px-3 py-1">
            Showing sample data — add BALLDONTLIE_API_KEY in .env.local for live games
          </p>
        )}
        {source === "error" && (
          <p className="text-xs text-buzzer mt-4 border border-buzzer/40 inline-block px-3 py-1">
            Couldn&apos;t load games right now{error ? `: ${error}` : ""}. Check your
            BALLDONTLIE_API_KEY in Vercel&apos;s environment variables.
          </p>
        )}
      </header>

      <AccuracyPanel stats={accuracy} recentForm={recentForm} />

      <section className="space-y-4">
        {games.length === 0 && source !== "error" && (
          <p className="text-sm text-chalk/50">No upcoming games in the next few days.</p>
        )}
        {games.map((g) => (
          <GameCard key={g.id} game={g} />
        ))}
      </section>

      <footer className="mt-14 text-xs text-chalk/40 leading-relaxed border-t border-line pt-6">
        Predictions are generated by a statistical model for informational
        purposes only and are not betting advice. Sports betting carries
        financial risk and is subject to local laws — check that it&apos;s
        legal in your jurisdiction before wagering. If gambling stops being
        fun, resources like the National Council on Problem Gambling
        (1-800-522-4700) can help.
      </footer>
    </main>
  );
}
